# Prediction configuration file
name_attr_config: 'xssa_attr_config.yaml'  # REQUIRED. Name of the corresponding dataset's attribute configuration file, which should be in the same directory as this. If not provided, assumes 'attr' may be substituted for this filename's 'algo'
name_algo_config: 'xssa_algo_config.yaml' # REQUIRED. The name of the algorithm configuration file if in same directory as this config file. Otherwise the full path to the file.
ds_type: 'prediction' # Required string. Strongly recommended to select 'prediction' in the prediction config file, but any string will work. This string will be used in the filename of the output metadata describing each data point's identifer, COMID, lat/lon, reach name of the location. This string should differ from the string used in the attribute config yaml file. Filename: `"nldi_feat_{dataset}_{ds_type}.csv"` inside `dir_std_base / dataset /`
write_type: 'parquet' # Required filetype for writing NLDI feature metadata. Default 'parquet'. May also select 'csv'
path_meta: "{dir_std_base}/{ds}/nldi_feat_{ds}_{ds_type}.{write_type}" # Required. Prediction attribute metadata filepath formatted for R's glue() & py f-strings as generated using `proc.attr.hydfab::write_meta_nldi_feat()`. Strongly suggested default format:  "{dir_std_base}/{ds}/nldi_feat_{ds}_{ds_type}.{write_type}"  
pred_file_comid_colname: 'comid'
path_attr_config: "{home_dir}/git/formulation-selector/scripts/eval_ingest/xssa/xssa_attr_config.yaml"
basepath_algos:
algo_response_vars: # List out the desired response variables (e.g. metrics, hydrologic signatures) for prediction. # TODO offer 'all'
  - 'NSE'
  - 'KGE'
algo_type: # List out the regressor rr43walgorithms desired for prediction (e.g. rf, mlp).  # TODO offer 'all'
  - 'rf'

