# Config for training and testing algorithms that predict formulation metrics or hydrologic signatures based on catchment attributes
algorithms: # REQUIRED. Refer to AlgoTrainEval.train_algos to see what options are present (e.g. rf, mlp)
  rf:  # STRONGLY RECOMMENDED. Refer to sklearn.ensemble.RandomForestRegressor for arguments to pass here. Otherwise defaults will be used
    - n_estimators: 100
  mlp:  # OPTIONAL. Refer to sklearn.neural_network.MLPRegressor for arguments to pass here. Otherwise defaults will be when 'mlp' is specified here
    - hidden_layer_sizes: (4,) # expect a tuple for hidden_layer_sizes, which will be interpreted as a string literal
    - activation: relu
    - solver: lbfgs
    - alpha: 0.001
    - batch_size: auto
    - learning_rate: constant
    - power_t: 0.5
    - max_iter: 20000
test_size: 0.3 # The proportion of dataset for testing, passed to sklearn.train_test_split
seed: 32 # the random seed
name_attr_config: 'xssa_attr_config.yaml'  # REQUIRED. Name of the corresponding dataset's attribute configuration file, which should be in the same directory as this. If not provided, assumes 'attr' may be substituted for this filename's 'algo'
verbose: True # Boolean. Should the train/test/eval provide printouts on progress?